/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.1.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    application
    id("org.springframework.boot") version "3.3.2"
    id("io.spring.dependency-management") version "1.1.5"
    id("java")
    id("org.sonarqube") version "5.0.0.4638"
    jacoco
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    implementation(libs.guava)

    implementation ("org.springframework.boot:spring-boot-starter-web")
    implementation ("org.springframework.boot:spring-boot-starter-data-jpa")
    
    // SQLite support
    runtimeOnly ("com.h2database:h2")
    runtimeOnly ("org.xerial:sqlite-jdbc:3.44.1.0")
    implementation ("org.hibernate.orm:hibernate-community-dialects:6.4.1.Final")
    
    // Jackson for JSON serialization (to avoid JsonBackReference issues)
    implementation ("com.fasterxml.jackson.core:jackson-databind:2.16.1")
    implementation ("com.fasterxml.jackson.core:jackson-annotations:2.16.1")
    
    testImplementation ("org.springframework.boot:spring-boot-starter-test")
}


java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    mainClass = "org.SportsIn.App"
}

tasks.named<Test>("test") {
    useJUnitPlatform()
    finalizedBy(tasks.jacocoTestReport)
}

tasks.jacocoTestReport {
    dependsOn(tasks.test)
    reports {
        xml.required = true
        html.required = true
    }
}

sonar {
    properties {
        property("sonar.projectKey", "AlvesMartim_SportsIn")
        property("sonar.organization", "alvesmartim")
        property("sonar.host.url", "https://sonarcloud.io")
        property("sonar.coverage.jacoco.xmlReportPaths", "${layout.buildDirectory.get()}/reports/jacoco/test/jacocoTestReport.xml")
    }
}

// Tâche pour construire le frontend avant le build
val frontendDir = rootProject.layout.projectDirectory.dir("frontend")
val frontendPackageJson = frontendDir.file("package.json")

tasks.register("installFrontendDependencies", Exec::class) {
    group = "build"
    description = "Install frontend npm dependencies"
    workingDir = rootProject.layout.projectDirectory.asFile
    commandLine("bash", "install-frontend.sh")
    onlyIf {
        frontendPackageJson.asFile.exists() && !frontendDir.file("node_modules").asFile.exists()
    }
}

tasks.register("buildFrontend", Exec::class) {
    group = "build"
    description = "Build the React frontend"
    workingDir = frontendDir.asFile
    commandLine("npm", "run", "build")
    dependsOn("installFrontendDependencies")
    // Ne s'exécute que si le dossier frontend existe et contient package.json et node_modules
    onlyIf {
        frontendPackageJson.asFile.exists() && frontendDir.file("node_modules").asFile.exists()
    }
}

// Faire en sorte que processResources dépende de buildFrontend
// DÉSACTIVÉ - La construction du frontend doit être faite manuellement
// Pour activer : décommentez les lignes ci-dessous et installez Node.js dans WSL
// tasks.named("processResources") {
//     dependsOn("buildFrontend")
// }
